### PR TITLE
[#361] Poetry v2 Migration - python inline dependencies fix

### LINKED ISSUE #361: Poetry v2 Migration - python inline dependencies fix
### Description
The current `PoetryToProjectRequiresPythonMigration` copies the `python` dependency from `tool.poetry.dependencies` to `project.requires-python` correctly but does not remove it from `tool.poetry.dependencies` when `dependencies` is provided as a inline table under the `[tool.poetry]` header. We should fix the migration to account for this case. In the situation that there are two python constraints in the `pyproject.toml`, we should prioritize the one under `project`.
**Actual:**
```
[tool.poetry]
dependencies = { python = "^3.12", ruff = "0.11.6" }

[project]
name = "test-project"
...
requires-python = ">=3.12,<4"
```

**Expected:**
```
[tool.poetry]
dependencies = { ruff = "0.11.6" }

[project]
name = "test-project"
...
requires-python = ">=3.12,<4"
```

### Definition of Done
- [x] update existing `PoetryToProjectRequiresPythonMigration` to remove the `python` version constraint after copying it to `project.requires-python`
- [x] update migration so that if there are 2 `python` version constraints listed (in `tool.poetry.dependencies` and `project.requires-python`), then prioritize `project.requires-python` and remove `python` from `tool.poetry.dependencies`
- [x] run updated migration against all `example` Poetry projects
- [x] update unit tests
- [x] update `README` to include info about multiple `python` version constraints

### Test Steps
1. Build `habushu-maven-plugin` by running the `bootstrap` profile - `mvn clean install -Pbootstrap`
2. Build example projects - `mvn clean install`
3. Change directory to `examples/poetry/habushu-poetry-package`. We will use the `pyproject.toml` in this directory as our test project

#### Case 1 - migrate `python` version constraint from `[tool.poetry.dependencies]` section to `project.requires-python`
4. Remove existing `project.requires-python` line, add `python = "^3.12"` version constraint under `[tool.poetry.dependencies]` header, and run the migration via `mvn habushu:baton-migrate`

> **Before**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> dynamic = ["version", "dependencies"]
> 
> [tool.poetry.dependencies]
> python = "^3.12"
> krausening = ">=20"
> ...
> ```

5. Confirm the `python` was removed from `[tool.poetry.dependencies]` section and `requires-python` was added to `[project]` section

> **After**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> requires-python = ">=3.12,<4"
> 
> [tool.poetry.dependencies]
> krausening = ">=20"
> ...
> ```

#### Case 2 - remove duplicate `python` version constraint from `[tool.poetry.dependencies]` section
6. Keep existing `project.requires-python` line, add `python = "^3.12"` back into `[tool.poetry.dependencies]` header, and run the migration via `mvn habushu:baton-migrate`

> **Before**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> dynamic = ["version", "dependencies"]
> requires-python = ">=3.12,<4"
> 
> [tool.poetry.dependencies]
> python = "^3.12"
> krausening = ">=20"
> ...
> ```

7. Confirm the `python` dependency was removed from the `[tool.poetry.dependencies]` section and the `requires-python` remained in the `[project]` section

> **After**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> requires-python = ">=3.12,<4"
> 
> [tool.poetry.dependencies]
> krausening = ">=20"
> ...
> ```

#### Case 3 - migrate `python` version constraint from `tool.poetry` inline dependencies table to `project.requires-python`

8. Remove existing `project.requires-python` line, remove `[tool.poetry.dependencies]` header and everything listed under it, add `[tool.poetry]` header with inline table (see `Before` below), and run the migration via `mvn habushu:baton-migrate`

> **Before**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> dynamic = ["version", "dependencies"]
> 
> [tool.poetry]
> dependencies = { python = "^3.12", krausening = ">=20" }
> ...
> ```

9. Confirm `python` was removed from the `dependencies` table in the [tool.poetry]` section and `requires-python` was added to `[project]` section

> **After**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> requires-python = ">=3.12,<4"
> 
> [tool.poetry]
> dependencies = { krausening =">=20" }
> ...
> ```

#### Case 4 - remove duplicate `python` version constraint from `tool.poetry` inline dependencies table

10. Keep existing `project.requires-python` line, add `[tool.poetry]` header with inline table (see `Before` below), and run the migration via `mvn habushu:baton-migrate`

> **Before**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> requires-python = ">=3.12,<4"
> 
> [tool.poetry]
> dependencies = { python = "^3.12" }
> ...
> ```

11. Confirm the entire `[tool.poetry]` section and inline table was removed and the `requires-python` remained in the `[project]` section

> **After**
> ```
> [project]
> name = "habushu_poetry_package"
> version = "3.0.0.dev"
> ...
> requires-python = ">=3.12,<4"
> 
> ...
> ```

### Notes/Additional Considerations
(For Poetry v2.0+) When running `poetry.lock` on a project that has different `python` version constraints in the `pyproject.toml`, the `project.requires-python` takes precedence
**Example**
```
[tool.poetry]
dependencies = { python = ">=3.11,<4"}

[project]
name = "test-project"
...
requires-python = ">=3.12.9,<4"
```
Will return the following error:
```
The Python constraint in [tool.poetry.dependencies] ">=3.11,<4" is not a subset of "requires-python" in [project] ">=3.12.9,<4"
```

### PR DESCRIPTION
**Pull request by chang-annie**
#361 
For Poetry v2 projects:
- accounts for inline tables when migration `python` version constraint from `tool.poetry.dependencies` to `project.requires-python`
- removes duplicate python dep from `pyproject.toml` if it exists
- deactivates a migration for the `habushu-poetry-install-from-dev-repo` example project

### CODE REVIEW

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 1]
```diff
@@ -11,72 +11,80 @@
...
                 tomlFileConfig.load();
-                Optional<Config> projectGroup = tomlFileConfig.getOptional(TomlUtils.PROJECT);
 
+                Optional<Config> poetryDependenciesGroup = tomlFileConfig.getOptional(TomlUtils.TOOL_POETRY_DEPENDENCIES); //tool.poetry.dependencies
+                if (poetryDependenciesGroup.isPresent()) {
+                    Config poetryDependenciesGroupEntry = poetryDependenciesGroup.get();
+
+                    if (poetryDependenciesGroupEntry.contains(TomlUtils.PYTHON)){
+                        hasPoetryPython = true;
+                        poetryDependenciesKeys = poetryDependenciesGroupEntry.entrySet().stream().map(Config.Entry::getKey).collect(Collectors.toList());
```
Comment (chang-annie) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:46]: I: keeping track of the keys under the `tool.poetry.dependencies` section so in the case we have inline dependencies table, we can check 1. how many dependencies are listed in the table & 2. what position `python` is in (which affects the regex we use to remove it)

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 2]
```diff
@@ -11,72 +11,80 @@
...
-                                pythonDependencyVersion = TomlUtils.refactorCarrotIntoGreaterThanLessThan(pythonDependencyVersion);
-                            }
-                        }
-                    }
                 }
             }
         }
-
-        return shouldExecute;
+        return missingRequiresPython || updateFaultyFormat || (!missingRequiresPython && hasPoetryPython);
```
Comment (chang-annie) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:79]: I: there are now 3 cases that should trigger this migration
1. the `project` section does NOT have `requires-python` field
2. the `project` section already has a `requires-python` field BUT it's using caret notation instead of >=,<
3. the `project` section already has a `requires-python` field AND it also has a `python` constraint in `tool.poetry.dependencies`

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 3]
```diff
@@ -87,43 +95,50 @@ protected boolean performMigration(File pyProjectTomlFile) {
...
                             injectAfterNextEmptyLine = true;
+                            missingRequiresPython = false;
+                        }
+                    } else if (TomlUtils.TOOL_POETRY.equals(currentSection) && hasInlineDependenciesTable && trimmedLine.contains(TomlUtils.DEPENDENCIES)){
+                        addLine = false;
+
+                        // Only need to remove python if other dependencies exist, otherwise we can just skip the line
+                        if (poetryDependenciesKeys.size() > 1){
+                            String regex;
+                            if(poetryDependenciesKeys.indexOf(TomlUtils.PYTHON) == poetryDependenciesKeys.size()-1){
```
Comment (chang-annie) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:129]: I: if `python` is the last entry in the inline table (e.g., `dependencies = { foo = "xyz", bar = "xyz", python = "xyz" }`), then we remove the preceding comma + `python = "xyz"`. 

Otherwise, (e.g., `dependencies = { python = "xyz", foo = "xyz", bar = "xyz" }`) we remove `python = "xyz"` + the trailing comma

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 4]
```diff
@@ -11,72 +11,80 @@
...
     protected boolean shouldExecuteOnFile(File file) {
-        boolean shouldExecute = false;
-
         if (isPoetryProject(file) && isPoetryVersionAtLeast2) {
             try (FileConfig tomlFileConfig = FileConfig.of(file)){
                 tomlFileConfig.load();
-                Optional<Config> projectGroup = tomlFileConfig.getOptional(TomlUtils.PROJECT);
 
+                Optional<Config> poetryDependenciesGroup = tomlFileConfig.getOptional(TomlUtils.TOOL_POETRY_DEPENDENCIES); //tool.poetry.dependencies
+                if (poetryDependenciesGroup.isPresent()) {
```
Comment (aaron-gary) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:41]: Q: Is this a comment or a leftover line of code?

**Review by aaron-gary — APPROVED** [review]

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java (hunk 4 above)
Comment (chang-annie) [reply habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:41]: removed the comment, good catch!

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/util/TomlUtils.java [hunk 5]
```diff
@@ -79,7 +79,20 @@ public final class TomlUtils {
...
      */
-    private static final String TOML_SECTION_HEADER_REGEX = "^\\[+(.+?)\\]+$";
+    private static final Pattern TOML_SECTION_HEADER_PATTERN = Pattern.compile("^\\[+(.+?)\\]+$");
+
+    /**
+     * Matches an inline Python dependency assignment in a TOML table
+     * using single/double quotes, and with optional whitespaces
+     * e.g. `python = ">=3.12.0,<4"`, `Python='^3.12'`
+     */
+    public static final Pattern PYTHON_DEPENDENCIES_PATTERN = Pattern.compile("(?i)\\bpython\\s*=\\s*(?:'[^']*'|\"[^\"]*\")");
```
Comment (epwilkins) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/util/TomlUtils.java]: A: couldn't you just do
```suggestion
    public static final Pattern PYTHON_DEPENDENCIES_PATTERN = Pattern.compile("\\bpython\\s*=\\s*('|\").*?('|\")");
```
Why do we need case-insensitive?

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 6]
```diff
@@ -87,43 +95,50 @@ protected boolean performMigration(File pyProjectTomlFile) {
...
+                            missingRequiresPython = false;
+                        }
+                    } else if (TomlUtils.TOOL_POETRY.equals(currentSection) && hasInlineDependenciesTable && trimmedLine.contains(TomlUtils.DEPENDENCIES)){
+                        addLine = false;
+
+                        // Only need to remove python if other dependencies exist, otherwise we can just skip the line
+                        if (poetryDependenciesKeys.size() > 1){
+                            String regex;
+                            if(poetryDependenciesKeys.indexOf(TomlUtils.PYTHON) == poetryDependenciesKeys.size()-1){
+                                // if python is the last element, we drop the preceding comma + python entry
```
Comment (epwilkins) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:130]: Q: Couldn't you make the trailing comma optional and just always drop it if present?

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java [hunk 7]
```diff
@@ -11,72 +11,80 @@
...
     protected boolean shouldExecuteOnFile(File file) {
-        boolean shouldExecute = false;
-
         if (isPoetryProject(file) && isPoetryVersionAtLeast2) {
             try (FileConfig tomlFileConfig = FileConfig.of(file)){
                 tomlFileConfig.load();
-                Optional<Config> projectGroup = tomlFileConfig.getOptional(TomlUtils.PROJECT);
 
+                Optional<Config> poetryDependenciesGroup = tomlFileConfig.getOptional(TomlUtils.TOOL_POETRY_DEPENDENCIES);
+                if (poetryDependenciesGroup.isPresent()) {
```
Comment (ewilkins-csi) [inline habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:41]: A; This is never false right? Why do we wrap a constant in an optional?

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java (hunk 6 above)
Comment (chang-annie) [reply habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/migration/poetryv2migrations/PoetryToProjectRequiresPythonMigration.java:130]: if we update the regex to add an optional trailing comma and `python` is the last item in an inline table, the preceding comma wouldn't be removed properly -
`dependencies = { foo = "xyz", bar = "xyz", }`

File: habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/util/TomlUtils.java (hunk 5 above)
Comment (chang-annie) [reply habushu-maven-plugin/src/main/java/org/technologybrewery/habushu/util/TomlUtils.java]: yes, you're right! no need for case-insensitive & simplified the regex as you suggested.

**Review by meliz19 — APPROVED** [review]
