### PR TITLE
[#414] add migration for updated configs

### LINKED ISSUE #409: Make new configuration skipLockUpdate backwards compatible
## Description
In #407 we updated the configuration `skipPoetryLockUpdate` to `skipLockUpdate`. We did not create a baton migration or still allow the old configuration name to be valid. This will cause existing projects to fail.

**DoD**
- [ ] Prevent existing projects with `skipPoetryLockUpdate` from failing on upgrade

**Testing Script**

### LINKED ISSUE #414: Containerization: Create Baton migrations to account for new wheel-based approach
We've updated our approach to containerizing Python applications in #410 and #411.  There were some deprecations/changes that will need to be accounted for in downstream projects.  We should automatically migrate users so that we can remove the deprecated logic entirely without breaking anything.

**Definition of Done**
- [x] Migration to change tool-specific template configs to generic config
- [x] Migration to remove deprecated configs:
  - defaultSourceSet
  - all poetry-specific configs
  - all uv-specific configs
- [x] Remove deprecated configs in Mojo

**Test Steps**
1. Build the `habushu-maven-plugin` in the Habushu repository
    ```sh
    mvn clean install -Pbootstrap
    ```
2. Create a test Habushu project with a parent POM (unzip [habushu-414-test.tar.gz](https://github.com/user-attachments/files/21843295/habushu-414-test.tar.gz))
    - _Note: this is a Git project, so git reset/diff is available_
3. Run the build with Habushu 3.1.1 to ensure the project builds
    ```sh
    mvn clean install
    ```
4. Update the Habushu version to 3.2.0-SNAPSHOT in the root POM
    ```diff
            <version.habushu>3.1.1</version.habushu>
            <version.habushu>3.2.0-SNAPSHOT</version.habushu>
    ```
5. Run the baton migration command as noted in the [draft release notes](https://github.com/TechnologyBrewery/habushu/releases/tag/untagged-f29adb72193e85ac35f5)
    - Note the warning printed about unknown parameters -- these are the properties that should be migrated
    ```sh
    [WARNING] Parameter 'dockerUvBuilderStageTemplatePath' is unknown for plugin 'habushu-maven-plugin:3.2.0-SNAPSHOT:baton-migrate (default-cli)'
    ...
    [WARNING] Parameter 'dockerPoetryVersion' is unknown for plugin 'habushu-maven-plugin:3.2.0-SNAPSHOT:baton-migrate (default-cli)'
    ```
6. Run the migration command again and verify no unknown parameter warnings are printed
7. Run the build to ensure success after migration
    ```sh
    mvn clean install
    ```

### PR DESCRIPTION
**Pull request by epwilkins**
Also fixes #409

### CODE REVIEW

File: habushu-maven-plugin/src/test/java/org/technologybrewery/habushu/migration/ConfigurationMigrationSteps.java [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+
+public class ConfigurationMigrationSteps {
+    private String scenario;
+    private Path testPom;
+    private boolean shouldExecute;
+    private boolean executionSucceeded;
+
+    @Before("@config-migration")
+    public void before(Scenario scenario) {
+        this.scenario = scenario.getName().toLowerCase().replaceAll("\\s+", "-");
```
Comment (epwilkins) [inline habushu-maven-plugin/src/test/java/org/technologybrewery/habushu/migration/ConfigurationMigrationSteps.java:39]: I: This allows us to save the test poms under different names so the results can be inspected more easily.

**Review by csun-cpointe — APPROVED** [review]

**Review by chang-annie — APPROVED** [review]
